# Generated by Django 5.1.1 on 2024-09-17 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_choice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='score',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='Question', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=6),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='New Quiz', max_length=120),
        ),
        migrations.AddField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(default=10, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(default=50, help_text='Required score in %'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default=30, help_text='Duration of the quiz in minutes'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(default='Choice', max_length=255),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Answer', max_length=255)),
                ('correct', models.BooleanField(default=False)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='QuizApp.question')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='QuizScore',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
