# Generated by Django 5.1.1 on 2024-09-17 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default='New Quiz', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='QuizApp.quiz'),
        ),
    ]
