# Generated by Django 4.1.1 on 2024-09-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0009_alter_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(default='Option 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(default='Option 2', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(default='Option 3', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(default='Option 4', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
