# Generated by Django 4.1.1 on 2024-09-24 11:54

from django.db import migrations, models
import django.db.models.deletion

def set_default_quiz(apps, schema_editor):
    UserAnswer = apps.get_model('QuizApp', 'UserAnswer')
    Quiz = apps.get_model('QuizApp', 'Quiz')
    default_quiz = Quiz.objects.first()
    for ua in UserAnswer.objects.all():
        ua.quiz = default_quiz
        ua.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0012_useranswer_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='quiz',
            field=models.ForeignKey(default='Quiz1', on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quiz'),
        ),
        migrations.RunPython(set_default_quiz, reverse_code=migrations.RunPython.noop),
    ]
