# Generated by Django 4.1.1 on 2024-09-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0014_alter_useranswer_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quiz'),
        ),
    ]
